sudo: false
language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

env:
  - LARAVEL_VERSION=5.0.*
  - LARAVEL_VERSION=5.1.*

before_script:
  - git clone --depth=50 --branch=2015.03 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core
  - mv ../ai-laravel ext/
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - mysql -e 'create database aimeos;'
  - echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'database' => 'aimeos', 'username' => 'root', 'password' => '', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET NAMES 'utf8'\", \"SET SESSION sql_mode='ANSI'\" ) ) );" > config/resource.php

script:
  - vendor/bin/phing -Ddir=ext/ai-laravel setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-laravel/.coveralls.yml
