sudo: false
language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

env:
  - LARAVEL_VERSION=5.0.*

before_script:
  - git clone --depth=50 --branch=master git://github.com/aimeos/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-laravel5 ext/
  - composer require "laravel/framework:${LARAVEL_VERSION}"

script:
  - vendor/bin/phing -Ddir=ext/ai-laravel5 setup coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-laravel5/.coveralls.yml